function T = RobotModelFK_Kuka(q,params,sigma,Tbase,Ttool)
T = Tbase*Rz(q(1))*Tx(params(1))*Ty(params(2))*Ry(params(3))* ...
Rx(q(2)+params(4))*Ty(params(5))*Tz(params(6))*Ry(params(7))* ...
Rz(q(3)+params(8))*Tx(params(9))*Ty(params(10))*Ry(params(11))* ...
Rx(q(4)+params(12))*Ty(params(13))*Tz(params(14))*Ry(params(15))* ...
Rz(q(5)+params(16))*Tx(params(17))*Ty(params(18))*Ry(params(19))* ...
Rx(q(6)+params(20))*Ty(params(21))*Tz(params(22))*Ry(params(23))* ...
Rz(q(7))*Ttool;
T(1:3,4) = T(1:3,4)+sigma*randn(3,1);
end
